### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by JordanRL** [eklundchristopher/name-gen#1]
I have a game I am working on that I was going to build a similar library for. This looks promising, however the README doesn't explain much. I can see from the code what you were going for, but do you have any guidelines for contribution, or what direction you want to take this?

**Comment by eklundchristopher** [comment]
Hi @JordanRL!

When I created this package, I really just needed a somewhat decent fantasy name generator for another project of mine, pandaac/pandaac. I based the formula off of http://rinkworks.com/namegen/ 

That being said, I don't really have a direction for the project, nor any guidelines, but I'd be happy to promote you to a collaborator if you'd like to take it further.
